version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:develop
    container_name: chatwoot
    hostname: chatwoot
    env_file: stack.env 
    stdin_open: true 
    tty: true  
    networks: 
      - proxy     
  rails:
    <<: *base
    container_name: chatwoot-rails
    hostname: chatwoot-rails
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    networks: 
      - proxy
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.chatwoot.entrypoints=websecure
      - traefik.http.routers.chatwoot.rule=Host(`wtp.nckti.com.br`)

  sidekiq:
    <<: *base
    container_name: chatwoot-sidekiq
    hostname: chatwoot-sidekiq
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    networks: 
      - proxy
    restart: unless-stopped
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: chatwoot-pgadmin4
    hostname: chatwoot-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "demo@demo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2021!"
    networks:
      - proxy

  redis:
    image: redis:alpine
    container_name: chatwoot-redis
    hostname: chatwoot-redis
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: stack.env
    volumes:
      - ./wppconnect-chatwoot/data/redis:/data
    networks: 
      - proxy

networks: 
  proxy:
    name: proxy